version: 0.2

phases:
  build:
    commands:
      - mvn clean
      - mvn install
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$ENV -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$COMMIT_HASH .
artifacts:
  files:
    - 'Dockerfile'
    - 'target/loginservice-0.0.1-SNAPSHOT.jar'