version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - docker login -u AWS -p password https://895164885144.dkr.ecr.us-east-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - cd docker-distribution
      - docker build -t 895164885144.dkr.ecr.us-east-1.amazonaws.com/team3ecrrepo/loginservice:latest .
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 895164885144.dkr.ecr.us-east-1.amazonaws.com/team3ecrrepo/loginservice:latest
      